// Generated by scripts/generate-icons.mjs. Do not edit by hand.
import type { IconName } from "./solar-icons.generated";

export const solarIconNames: IconName[] = ["home", "upload", "user", "users", "list", "briefcase", "chart", "file", "document", "folder", "settings", "search", "filter", "close", "chevron-right", "chevron-down", "arrow-right", "plus", "edit", "trash", "star", "bell", "calendar", "check", "alert", "info", "scan", "brain", "target", "ranking", "medal", "sparkles", "shield", "download", "clock", "refresh", "lock", "mail", "card", "menu", "logout", "building", "bolt", "wand", "global", "eye", "eye-closed"];
