// Copies the Solar icons we use into source so nothing ships as a runtime dependency.
// Solar Icon Set by 480 Design, CC BY 4.0: https://creativecommons.org/licenses/by/4.0/
// Usage: node scripts/generate-icons.mjs
import { readFileSync, writeFileSync } from "node:fs";

const solar = JSON.parse(readFileSync("node_modules/@iconify-json/solar/icons.json", "utf8"));

// Semantic app name -> Solar base name. Add a line here, then re-run the script.
const ICONS = {
  home: "home-2",
  upload: "upload-minimalistic",
  user: "user",
  users: "users-group-rounded",
  list: "list-check",
  briefcase: "case-minimalistic",
  chart: "graph-up",
  message: "chat-round-dots",
  file: "document-text",
  document: "document",
  folder: "folder-with-files",
  settings: "settings",
  search: "magnifier",
  filter: "filter",
  close: "close-circle",
  "chevron-right": "alt-arrow-right",
  "chevron-down": "alt-arrow-down",
  "arrow-right": "arrow-right",
  plus: "add-circle",
  edit: "pen",
  trash: "trash-bin-trash",
  star: "star",
  bell: "bell",
  calendar: "calendar",
  check: "check-circle",
  alert: "danger-triangle",
  info: "info-circle",
  scan: "eye-scan",
  brain: "brain",
  target: "target",
  ranking: "ranking",
  medal: "medal-ribbon",
  sparkles: "stars",
  shield: "shield-check",
  download: "download-minimalistic",
  clock: "clock-circle",
  refresh: "restart",
  lock: "lock-keyhole",
  mail: "letter",
  card: "card",
  menu: "hamburger-menu",
  logout: "logout-2",
  building: "buildings-2",
  bolt: "bolt",
  wand: "magic-wand-2",
  global: "global",
  eye: "eye",
  "eye-closed": "eye-closed",
};

function body(name) {
  const icon = solar.icons[name];
  if (!icon) throw new Error(`Missing Solar icon: ${name}`);
  return icon.body;
}

const entries = Object.entries(ICONS).map(([key, base]) => {
  const bold = solar.icons[`${base}-bold`] ? body(`${base}-bold`) : body(`${base}-linear`);
  return `  ${JSON.stringify(key)}: { linear: ${JSON.stringify(body(`${base}-linear`))}, bold: ${JSON.stringify(bold)} },`;
});

const nameList = Object.keys(ICONS)
  .map((key) => JSON.stringify(key))
  .join(", ");

const names = Object.keys(ICONS)
  .map((key) => JSON.stringify(key))
  .join(" | ");

writeFileSync(
  "components/ui/solar-icons.generated.ts",
  `// Generated by scripts/generate-icons.mjs. Do not edit by hand.
// Solar Icon Set by 480 Design, licensed CC BY 4.0.

export type IconName = ${names};

export const solarIcons: Record<IconName, { linear: string; bold: string }> = {
${entries.join("\n")}
};
`,
);
writeFileSync(
  "components/ui/icon-names.ts",
  `// Generated by scripts/generate-icons.mjs. Do not edit by hand.
import type { IconName } from "./solar-icons.generated";

export const solarIconNames: IconName[] = [${nameList}];
`,
);
console.log(`Wrote ${entries.length} icons`);
